### PR TITLE
возвращаемся на aws. нул-ресурс всем нравился, но там какие-то дохлые…

### PR DESCRIPTION
**Pull request by run0ut**
… ноды

### CODE REVIEW

**Comment by run0ut** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/home/sergey/bin/terraform plan -input=false -refresh -out \"/home/sergey/.atlantis/repos/run0ut/terraform-aws-74/2/default/default.tfplan\"" in "/home/sergey/.atlantis/repos/run0ut/terraform-aws-74/2/default": exit status 1
Releasing state lock. This may take a few moments...
╷
│ Error: Invalid index
│ 
│   on aws.tf line 56, in resource "aws_instance" "ubuntu_count":
│   56:   instance_type = local.web_instance_type_map[terraform.workspace]
│     ├────────────────
│     │ local.web_instance_type_map is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on aws.tf line 57, in resource "aws_instance" "ubuntu_count":
│   57:   count         = local.web_instance_count_map[terraform.workspace]
│     ├────────────────
│     │ local.web_instance_count_map is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on aws.tf line 75, in resource "aws_instance" "ubuntu_for_each":
│   75:   instance_type = local.web_instance_type_map[terraform.workspace]
│     ├────────────────
│     │ local.web_instance_type_map is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on aws.tf line 76, in resource "aws_instance" "ubuntu_for_each":
│   76:   for_each      = local.web_instance_for_each_map[terraform.workspace]
│     ├────────────────
│     │ local.web_instance_for_each_map is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵

```
</details>

**Comment by run0ut** [comment]
atlantis plan -w stage

**Comment by run0ut** [comment]
Ran Plan for dir: `.` workspace: `stage`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_instance.ubuntu_count[0] will be created
+ resource "aws_instance" "ubuntu_count" {
      + ami                                  = "ami-06dc723a718471e54"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = true
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = 1
      + cpu_threads_per_core                 = 2
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = false
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "ubuntu_count_stage_0"
        }
      + tags_all                             = {
          + "Name" = "ubuntu_count_stage_0"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

  # aws_instance.ubuntu_for_each["s1"] will be created
+ resource "aws_instance" "ubuntu_for_each" {
      + ami                                  = "ami-06dc723a718471e54"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = true
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = 1
      + cpu_threads_per_core                 = 2
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = false
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "Netology 74, s1"
        }
      + tags_all                             = {
          + "Name" = "Netology 74, s1"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ aws_metadata_account_id      = "564619220947"
+ aws_metadata_region          = "ec2.eu-north-1.amazonaws.com"
+ aws_metadata_user_id         = "AIDAYG5PNS7J3ZPE5O5RB"
+ aws_net_private_ip           = [
      + (known after apply),
    ]
+ aws_net_private_ip__for_each = [
      + (known after apply),
    ]
+ aws_net_subnet_id            = [
      + (known after apply),
    ]
+ aws_net_subnet_id__for_each  = [
      + (known after apply),
    ]
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -w stage`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.run0ut.ru/lock?id=run0ut%252Fterraform-aws-74%252F.%252Fstage)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -w stage`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by SergeyShadurskiy2 — APPROVED** [review]
Норм

**Comment by run0ut** [comment]
atlantis apply -w stage

**Comment by run0ut** [comment]
Ran Apply for dir: `.` workspace: `stage`

<details><summary>Show Output</summary>

```diff
aws_instance.ubuntu_count[0]: Creating...
aws_instance.ubuntu_for_each["s1"]: Creating...
aws_instance.ubuntu_count[0]: Still creating... [10s elapsed]
aws_instance.ubuntu_for_each["s1"]: Still creating... [10s elapsed]
aws_instance.ubuntu_count[0]: Creation complete after 15s [id=i-08e7a3096a6370595]
aws_instance.ubuntu_for_each["s1"]: Creation complete after 15s [id=i-0701309cec72abad0]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

aws_metadata_account_id = "564619220947"
aws_metadata_region = "ec2.eu-north-1.amazonaws.com"
aws_metadata_user_id = "AIDAYG5PNS7J3ZPE5O5RB"
aws_net_private_ip = [
  "172.31.13.96",
]
aws_net_private_ip__for_each = toset([
  "172.31.3.119",
])
aws_net_subnet_id = [
  "subnet-06f7d1def39a73fd4",
]
aws_net_subnet_id__for_each = toset([
  "subnet-06f7d1def39a73fd4",
])

```
</details>

**Comment by run0ut** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `stage`

**Pull request merged**
